build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: ndarray_listener
    PYTHON: "C:\\Python36-x64"

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - pip install -U setuptools pip pypandoc
    - python setup.py test && git clean -xdf
    - pip install . && git clean -xdf
    - cd ~/
    - python -c "import sys; import $PKG_NAME; sys.exit($PKG_NAME.test())"
    - pip uninstall $PKG_NAME --yes
    - cd $TRAVIS_BUILD_DIR && git clean -xdf
    - pip install -r requirements.txt
    - cd doc/ && make html && cd ..
    - git clean -xdf
    - python setup.py sdist
