build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: ndarray_listener
    PYTHON: "C:\\Python36-x64"

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - pip install -U setuptools pip pypandoc
    - python setup.py test && git clean -xdf && pip install .

test_script:
    - cd C:\
    - python -c "import sys; import %PKG_NAME%; sys.exit(%PKG_NAME%.test())"
