language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.5
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- travis_retry conda install pycparser -y --name travisci
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import ndarray_listener; ndarray_listener.test()"
- popd
deploy:
  provider: pypi
  skip_cleanup: true
  user: danilo.horta
  on:
    branch: master
  password:
    secure: BFkQOalcHtOMrlNY3TutMZpoan5gkqNSwwqxS/vu2BoYggK6COA48aVJTTwDWPUpH28UpPOgoOt66KtABNCpMh0cDBWRpel9xUGocQPWsrJpHBi7phuq76Nd6HO2e7aMh29JJLfNuZT3tjBdegi0DZOf4mHz4naFx75BIewAYUS92819FtQzBZmdDc+9se5+TylH6Pr4GKeQOTPCWGV5ZmSTqqwILUKq5R4yfwHCpQHejNTDqrtj1nlL5+IyUw6kGvdBlbnIX4eJYieod+ir7Y/BMRWhud7oKC3jtSt09fv4aiIrLecIJow2rSy4Qz2l8Fy/JkqA6LLKCMXlFZ9l35qv+hleUFGaiRcVTEAkh6c831Li0p1tJZVw5e1QF6SZ6BmrohmMPlaXV5M1xmNQlNsZ8XNxY7hGSG64lkcFSBKet6UOGPSF+LUNnkikPHKBFT9h98SIAT0Y/OgaEq6OZTwFXAgiz534l0O44bbw9SMk+PWmXrYGcyJGAy6yzWKixLrIG3KOw9wcrXJtP4xo1vaXyg1JvaB9bZFo4FOmV/61Der7gkvYRMkOqgK0pG9DVzUyBgWQw8O4iTvqTVkpeRA+ibsGw+hhSUlekFR7jaV+nvZYaFGJMpjc9CF6x8DOL5GdsvJ8xux2K6OGFKOqw3KBKwMS8z6ahk4P4EHStPw=
notifications:
  email: false
